os: Visual Studio 2017

version: 1.0.{build}.{branch}

init:
  - git config --global core.autocrlf input

install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version

  - cmd: dotnet restore ./src/Gogokit/Gogokit.csproj --verbosity m

build_script:
  - cmd: dotnet build --configuration release ./src/Gogokit/Gogokit.csproj

test_script:    
  - cmd: dotnet test ./tests/Gogokit.Tests/Gogokit.Tests.csproj

deploy:

  - provider: NuGet
    api_key:
      secure: $(NUGET_API_KEY)
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: KkZc/MtbfhwnJ7sfv74IFidwvYQmKLlmrO9yp4ydi30A+0XAP9c5frqd6f6PEZ7J
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
      
nuget:
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '.\src\Gogokit\bin\release\*.nupkg'
    name: Packages
